from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether
)
from reportlab.pdfbase.pdfmetrics import stringWidth

import os
import re
from datetime import datetime


# ============================================================
# COLORS
# ============================================================

NAVY = colors.HexColor("#0F172A")
DARK = colors.HexColor("#111827")
PURPLE = colors.HexColor("#6D28D9")
PURPLE_LIGHT = colors.HexColor("#8B5CF6")

CYAN = colors.HexColor("#0891B2")
GREEN = colors.HexColor("#16A34A")
RED = colors.HexColor("#DC2626")
ORANGE = colors.HexColor("#EA580C")

WHITE = colors.white
LIGHT_BG = colors.HexColor("#F8FAFC")
LIGHT_GRAY = colors.HexColor("#E2E8F0")
MEDIUM_GRAY = colors.HexColor("#64748B")
DARK_GRAY = colors.HexColor("#334155")


# ============================================================
# OUTPUT DIRECTORY
# ============================================================

REPORT_DIR = os.path.join(
    "outputs",
    "reports"
)

os.makedirs(
    REPORT_DIR,
    exist_ok=True
)


# ============================================================
# SAFE FILE NAME
# ============================================================

def safe_filename(name):

    name = str(name)

    name = re.sub(
        r'[<>:"/\\|?*]',
        '',
        name
    )

    name = re.sub(
        r'\s+',
        '_',
        name
    )

    if not name:
        name = "candidate"

    return name[:80]


# ============================================================
# FORMAT PERCENTAGE
# ============================================================

def format_percentage(value):

    try:
        return f"{float(value):.1f}%"
    except:
        return "0.0%"


# ============================================================
# SCORE COLOR
# ============================================================

def score_color(score):

    try:
        score = float(score)
    except:
        score = 0

    if score >= 80:
        return GREEN

    if score >= 60:
        return ORANGE

    return RED


# ============================================================
# PAGE HEADER / FOOTER
# ============================================================

def draw_page(canvas, document):

    canvas.saveState()

    width, height = A4

    # --------------------------------------------
    # TOP LINE
    # --------------------------------------------

    canvas.setStrokeColor(
        PURPLE
    )

    canvas.setLineWidth(
        2
    )

    canvas.line(
        18 * mm,
        height - 15 * mm,
        width - 18 * mm,
        height - 15 * mm
    )

    # --------------------------------------------
    # HEADER
    # --------------------------------------------

    canvas.setFont(
        "Helvetica-Bold",
        8
    )

    canvas.setFillColor(
        NAVY
    )

    canvas.drawString(
        18 * mm,
        height - 11 * mm,
        "RESUMEIQ"
    )

    canvas.setFont(
        "Helvetica",
        7
    )

    canvas.setFillColor(
        MEDIUM_GRAY
    )

    canvas.drawRightString(
        width - 18 * mm,
        height - 11 * mm,
        "AI RECRUITMENT INTELLIGENCE"
    )

    # --------------------------------------------
    # FOOTER LINE
    # --------------------------------------------

    canvas.setStrokeColor(
        LIGHT_GRAY
    )

    canvas.setLineWidth(
        0.5
    )

    canvas.line(
        18 * mm,
        14 * mm,
        width - 18 * mm,
        14 * mm
    )

    # --------------------------------------------
    # FOOTER
    # --------------------------------------------

    canvas.setFont(
        "Helvetica",
        7
    )

    canvas.setFillColor(
        MEDIUM_GRAY
    )

    canvas.drawString(
        18 * mm,
        9 * mm,
        "Generated by ResumeIQ"
    )

    canvas.drawRightString(
        width - 18 * mm,
        9 * mm,
        f"Page {document.page}"
    )

    canvas.restoreState()


# ============================================================
# SECTION TITLE
# ============================================================

def section_title(text):

    return Paragraph(
        text.upper(),
        ParagraphStyle(
            "SectionTitle",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=NAVY,
            spaceBefore=12,
            spaceAfter=7,
        )
    )


# ============================================================
# NORMAL TEXT
# ============================================================

def normal_text(text):

    return Paragraph(
        str(text),
        ParagraphStyle(
            "NormalText",
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=DARK_GRAY,
            spaceAfter=5,
        )
    )


# ============================================================
# SMALL TEXT
# ============================================================

def small_text(text):

    return Paragraph(
        str(text),
        ParagraphStyle(
            "SmallText",
            fontName="Helvetica",
            fontSize=7.5,
            leading=10,
            textColor=MEDIUM_GRAY,
        )
    )


# ============================================================
# CREATE SCORE CARD
# ============================================================

def score_card(
    title,
    value,
    accent
):

    title_style = ParagraphStyle(
        "ScoreTitle",
        fontName="Helvetica-Bold",
        fontSize=7,
        leading=9,
        textColor=MEDIUM_GRAY,
        alignment=TA_CENTER
    )

    value_style = ParagraphStyle(
        "ScoreValue",
        fontName="Helvetica-Bold",
        fontSize=17,
        leading=20,
        textColor=accent,
        alignment=TA_CENTER
    )

    data = [[
        Paragraph(
            title.upper(),
            title_style
        )
    ], [
        Paragraph(
            format_percentage(value),
            value_style
        )]]

    table = Table(
        data,
        colWidths=[
            38 * mm
        ],
        rowHeights=[
            12 * mm,
            16 * mm
        ]
    )

    table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                LIGHT_BG
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.7,
                LIGHT_GRAY
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                3
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                3
            ),
        ])
    )

    return table


# ============================================================
# LIST TO TEXT
# ============================================================

def skills_text(
    skills,
    symbol="•"
):

    if not skills:
        return "None detected"

    result = []

    for skill in skills:

        skill = str(skill).strip()

        if skill:
            result.append(
                f"{symbol} {skill}"
            )

    return "<br/>".join(
        result
    )


# ============================================================
# GENERATE REPORT
# ============================================================

def generate_report(

    candidate_name,

    predicted_role,

    confidence,

    resume_score,

    match_score,

    similarity_score,

    skill_score,

    skills,

    matched_skills,

    missing_skills

):

    # --------------------------------------------
    # NORMALIZE VALUES
    # --------------------------------------------

    try:
        confidence = float(
            confidence
        )
    except:
        confidence = 0

    try:
        resume_score = float(
            resume_score
        )
    except:
        resume_score = 0

    try:
        match_score = float(
            match_score
        )
    except:
        match_score = 0

    try:
        similarity_score = float(
            similarity_score
        )
    except:
        similarity_score = 0

    try:
        skill_score = float(
            skill_score
        )
    except:
        skill_score = 0

    skills = skills or []

    matched_skills = matched_skills or []

    missing_skills = missing_skills or []

    # --------------------------------------------
    # FINAL SCORE
    # --------------------------------------------

    final_score = (
        match_score * 0.60
        + resume_score * 0.25
        + confidence * 0.15
    )

    # --------------------------------------------
    # RECOMMENDATION
    # --------------------------------------------

    if final_score >= 80:

        recommendation = "SHORTLIST"

        recommendation_text = (
            "The candidate demonstrates strong alignment "
            "with the selected job requirements and is "
            "recommended for the next stage of recruitment."
        )

        recommendation_color = GREEN

    elif final_score >= 65:

        recommendation = "REVIEW"

        recommendation_text = (
            "The candidate shows reasonable alignment "
            "with the role. Additional HR review is "
            "recommended before making a final decision."
        )

        recommendation_color = ORANGE

    else:

        recommendation = "LOW MATCH"

        recommendation_text = (
            "The candidate currently shows limited "
            "alignment with the selected job requirements. "
            "Review skill gaps before proceeding."
        )

        recommendation_color = RED

    # --------------------------------------------
    # FILE NAME
    # --------------------------------------------

    clean_name = safe_filename(
        candidate_name
    )

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    filename = (
        f"{clean_name}_"
        f"screening_report_"
        f"{timestamp}.pdf"
    )

    filepath = os.path.join(
        REPORT_DIR,
        filename
    )

    # --------------------------------------------
    # DOCUMENT
    # --------------------------------------------

    document = SimpleDocTemplate(

        filepath,

        pagesize=A4,

        rightMargin=18 * mm,

        leftMargin=18 * mm,

        topMargin=25 * mm,

        bottomMargin=20 * mm,

        title="ResumeIQ Screening Report",

        author="ResumeIQ",

        subject="AI Resume Screening Report"
    )

    story = []

    # ========================================================
    # COVER / TITLE
    # ========================================================

    story.append(
        Spacer(
            1,
            5 * mm
        )
    )

    title_style = ParagraphStyle(
        "MainTitle",
        fontName="Helvetica-Bold",
        fontSize=25,
        leading=29,
        textColor=NAVY,
        alignment=TA_CENTER
    )

    story.append(
        Paragraph(
            "RESUMEIQ",
            title_style
        )
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=MEDIUM_GRAY,
        alignment=TA_CENTER
    )

    story.append(
        Paragraph(
            "AI-POWERED RESUME SCREENING REPORT",
            subtitle_style
        )
    )

    story.append(
        Spacer(
            1,
            10 * mm
        )
    )

    # ========================================================
    # CANDIDATE INFORMATION
    # ========================================================

    story.append(
        section_title(
            "Candidate Information"
        )
    )

    candidate_table_data = [

        [
            Paragraph(
                "<b>Candidate</b>",
                normal_style()
            ),

            Paragraph(
                str(candidate_name),
                normal_style()
            )
        ],

        [
            Paragraph(
                "<b>Predicted Role</b>",
                normal_style()
            ),

            Paragraph(
                str(predicted_role),
                normal_style()
            )
        ],

        [
            Paragraph(
                "<b>ML Confidence</b>",
                normal_style()
            ),

            Paragraph(
                format_percentage(
                    confidence
                ),
                normal_style()
            )
        ],

        [
            Paragraph(
                "<b>Report Generated</b>",
                normal_style()
            ),

            Paragraph(
                datetime.now().strftime(
                    "%d %B %Y, %I:%M %p"
                ),
                normal_style()
            )
        ]
    ]

    candidate_table = Table(
        candidate_table_data,
        colWidths=[
            45 * mm,
            125 * mm
        ]
    )

    candidate_table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                LIGHT_BG
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                LIGHT_GRAY
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7
            )
        ])
    )

    story.append(
        candidate_table
    )

    # ========================================================
    # OVERALL SCORE
    # ========================================================

    story.append(
        section_title(
            "Overall Screening Score"
        )
    )

    overall_style = ParagraphStyle(
        "Overall",
        fontName="Helvetica-Bold",
        fontSize=30,
        leading=34,
        textColor=score_color(
            final_score
        ),
        alignment=TA_CENTER
    )

    overall_label = ParagraphStyle(
        "OverallLabel",
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=MEDIUM_GRAY,
        alignment=TA_CENTER
    )

    overall_table = Table(
        [

            [
                Paragraph(
                    format_percentage(
                        final_score
                    ),
                    overall_style
                )
            ],

            [
                Paragraph(
                    "FINAL CANDIDATE RANKING SCORE",
                    overall_label
                )
            ]

        ],

        colWidths=[
            70 * mm
        ],

        rowHeights=[
            18 * mm,
            9 * mm
        ]
    )

    overall_table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                LIGHT_BG
            ),

            (
                "BOX",
                (0, 0),
                (-1, -1),
                1.2,
                score_color(
                    final_score
                )
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            )
        ])
    )

    story.append(
        Table(
            [[
                overall_table
            ]],
            colWidths=[
                174 * mm
            ],
            style=[
                (
                    "ALIGN",
                    (0, 0),
                    (-1, -1),
                    "CENTER"
                )
            ]
        )
    )

    story.append(
        Spacer(
            1,
            5 * mm
        )
    )

    # ========================================================
    # SCORE BREAKDOWN
    # ========================================================

    score_row = Table(

        [[

            score_card(
                "Job Match",
                match_score,
                score_color(
                    match_score
                )
            ),

            score_card(
                "Resume Quality",
                resume_score,
                score_color(
                    resume_score
                )
            ),

            score_card(
                "Skill Match",
                skill_score,
                score_color(
                    skill_score
                )
            ),

            score_card(
                "Similarity",
                similarity_score,
                score_color(
                    similarity_score
                )
            )

        ]],

        colWidths=[
            43 * mm,
            43 * mm,
            43 * mm,
            43 * mm
        ]
    )

    score_row.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP"
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                2
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                2
            )
        ])
    )

    story.append(
        score_row
    )

    # ========================================================
    # AI RECOMMENDATION
    # ========================================================

    story.append(
        section_title(
            "AI Recommendation"
        )
    )

    recommendation_table = Table(

        [[

            Paragraph(
                f"<b>{recommendation}</b>",
                ParagraphStyle(
                    "Recommendation",
                    fontName="Helvetica-Bold",
                    fontSize=14,
                    textColor=recommendation_color,
                    alignment=TA_CENTER
                )
            ),

            Paragraph(
                recommendation_text,
                ParagraphStyle(
                    "RecommendationText",
                    fontName="Helvetica",
                    fontSize=8.5,
                    leading=12,
                    textColor=DARK_GRAY
                )
            )

        ]],

        colWidths=[
            42 * mm,
            128 * mm
        ]
    )

    recommendation_table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (0, 0),
                LIGHT_BG
            ),

            (
                "BACKGROUND",
                (1, 0),
                (1, 0),
                colors.white
            ),

            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.7,
                LIGHT_GRAY
            ),

            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.5,
                LIGHT_GRAY
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                9
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                9
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                9
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                9
            )
        ])
    )

    story.append(
        recommendation_table
    )

    # ========================================================
    # DETECTED SKILLS
    # ========================================================

    story.append(
        section_title(
            "Detected Skills"
        )
    )

    detected = (
        skills_text(
            skills,
            "•"
        )
    )

    detected_table = Table(

        [[
            Paragraph(
                detected,
                ParagraphStyle(
                    "SkillText",
                    fontName="Helvetica",
                    fontSize=8.5,
                    leading=14,
                    textColor=DARK_GRAY
                )
            )
        ]],

        colWidths=[
            170 * mm
        ]
    )

    detected_table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                LIGHT_BG
            ),

            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                LIGHT_GRAY
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                8
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                8
            )
        ])
    )

    story.append(
        detected_table
    )

    # ========================================================
    # SKILL ANALYSIS
    # ========================================================

    story.append(
        section_title(
            "Skill Analysis"
        )
    )

    matched = skills_text(
        matched_skills,
        "✓"
    )

    missing = skills_text(
        missing_skills,
        "✗"
    )

    skill_analysis = Table(

        [[

            Paragraph(
                "<b>MATCHED SKILLS</b>",
                ParagraphStyle(
                    "MatchedTitle",
                    fontName="Helvetica-Bold",
                    fontSize=8,
                    textColor=GREEN
                )
            ),

            Paragraph(
                "<b>SKILL GAPS</b>",
                ParagraphStyle(
                    "MissingTitle",
                    fontName="Helvetica-Bold",
                    fontSize=8,
                    textColor=RED
                )
            )

        ],

        [

            Paragraph(
                matched,
                ParagraphStyle(
                    "MatchedText",
                    fontName="Helvetica",
                    fontSize=8,
                    leading=13,
                    textColor=DARK_GRAY
                )
            ),

            Paragraph(
                missing,
                ParagraphStyle(
                    "MissingText",
                    fontName="Helvetica",
                    fontSize=8,
                    leading=13,
                    textColor=DARK_GRAY
                )
            )

        ]],

        colWidths=[
            85 * mm,
            85 * mm
        ]
    )

    skill_analysis.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (0, 0),
                colors.HexColor("#F0FDF4")
            ),

            (
                "BACKGROUND",
                (1, 0),
                (1, 0),
                colors.HexColor("#FEF2F2")
            ),

            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                LIGHT_GRAY
            ),

            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.5,
                LIGHT_GRAY
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP"
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                8
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                8
            )
        ])
    )

    story.append(
        skill_analysis
    )

    # ========================================================
    # METHODOLOGY
    # ========================================================

    story.append(
        section_title(
            "Screening Methodology"
        )
    )

    methodology = (
        "ResumeIQ combines Natural Language Processing, "
        "TF-IDF based text representation, machine learning "
        "classification, skill extraction and job-description "
        "matching. The final candidate score combines job "
        "match, resume quality and ML confidence."
    )

    story.append(
        normal_text(
            methodology
        )
    )

    # ========================================================
    # DISCLAIMER
    # ========================================================

    story.append(
        Spacer(
            1,
            5 * mm
        )
    )

    disclaimer = (
        "<b>Important:</b> This report is an AI-assisted "
        "screening tool. It should support, not replace, "
        "human recruitment judgment. Final hiring decisions "
        "should consider interviews, qualifications, "
        "experience and other relevant factors."
    )

    disclaimer_table = Table(

        [[
            Paragraph(
                disclaimer,
                ParagraphStyle(
                    "Disclaimer",
                    fontName="Helvetica",
                    fontSize=7.5,
                    leading=11,
                    textColor=DARK_GRAY
                )
            )
        ]],

        colWidths=[
            170 * mm
        ]
    )

    disclaimer_table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                colors.HexColor("#FFFBEB")
            ),

            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.6,
                colors.HexColor("#FDE68A")
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                8
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                8
            )
        ])
    )

    story.append(
        disclaimer_table
    )

    # ========================================================
    # BUILD PDF
    # ========================================================

    document.build(
        story,
        onFirstPage=draw_page,
        onLaterPages=draw_page
    )

    return filepath


# ============================================================
# NORMAL STYLE HELPER
# ============================================================

def normal_style():

    return ParagraphStyle(
        "TableNormal",
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=DARK_GRAY
    )


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    print(
        "Testing ResumeIQ PDF generator..."
    )

    path = generate_report(

        "John Doe",

        "Machine Learning Engineer",

        87.5,

        90,

        84,

        72,

        91,

        [
            "Python",
            "Machine Learning",
            "Pandas",
            "NumPy",
            "SQL",
            "Scikit-learn",
            "TensorFlow"
        ],

        [
            "Python",
            "Machine Learning",
            "Pandas",
            "SQL",
            "Scikit-learn"
        ],

        [
            "Docker",
            "AWS"
        ]
    )

    print(
        "PDF CREATED SUCCESSFULLY"
    )

    print(
        path
    )